/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ModeloDatos.Empresa;
import ModeloDatos.EscribirMongoDB;
import ModeloDatos.LeerMongoDB;
import ModeloDatos.Personaje;
import ModeloDatos.Saga;
import ModeloDatos.Videojuego;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author alexP
 */
public class Ventana extends javax.swing.JFrame {

    int seleccionar = -1;
    private ArrayList<Empresa>listaEmpresas = new ArrayList<>();
    private ArrayList<Saga>listaSagas = new ArrayList<>();
    private ArrayList<Videojuego>listaVideojuegos = new ArrayList<>();
    private ArrayList<Personaje>listaPersonajes = new ArrayList<>();
    private EscribirMongoDB crearFichero = new EscribirMongoDB();
    private LeerMongoDB leerFichero = new LeerMongoDB();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        CargarArraysDeDatos();
        CargarDatosEmpresaEnVista();
        CargarDatosSagaEnVista();
        CargarDatosVideojuegoEnVista();
        CargarDatosPersonajeEnVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel_empresa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_empresa = new javax.swing.JTable();
        jButton_aniadir_empresa = new javax.swing.JButton();
        jButton_modificar_empresa = new javax.swing.JButton();
        jButton_borrar_empresa = new javax.swing.JButton();
        jLabel_nombre_empresa = new javax.swing.JLabel();
        jLabel_pais_sede = new javax.swing.JLabel();
        jLabel_fecha_fundacion = new javax.swing.JLabel();
        jTextField_nombre_empresa = new javax.swing.JTextField();
        jTextField_pais_sede = new javax.swing.JTextField();
        jTextField_fecha_fundacion = new javax.swing.JTextField();
        jButton_guardar_empresa = new javax.swing.JButton();
        jButton_cancelar_empresa = new javax.swing.JButton();
        jTextField_director_ejecutivo = new javax.swing.JTextField();
        jLabel_director_ejecutivo = new javax.swing.JLabel();
        jPanel_saga = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_saga = new javax.swing.JTable();
        jLabel_nombre_saga = new javax.swing.JLabel();
        jLabel_desarrolladora = new javax.swing.JLabel();
        jLabel_anio_creacion = new javax.swing.JLabel();
        jTextField_nombre_saga = new javax.swing.JTextField();
        jTextField_desarrolladora = new javax.swing.JTextField();
        jTextField_anio_creacion = new javax.swing.JTextField();
        jButton_guardar_saga = new javax.swing.JButton();
        jButton_cancelar_saga = new javax.swing.JButton();
        jButton_aniadir_saga = new javax.swing.JButton();
        jButton_modificar_saga = new javax.swing.JButton();
        jButton_borrar_saga = new javax.swing.JButton();
        jComboBox_compania = new javax.swing.JComboBox<>();
        jLabel_compania_pertenece_saga = new javax.swing.JLabel();
        jLabel_genero = new javax.swing.JLabel();
        jTextField_genero = new javax.swing.JTextField();
        jPanel_videojuego = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_videojuego = new javax.swing.JTable();
        jLabel_nombre_videojuego = new javax.swing.JLabel();
        jLabel_motor_videojuego = new javax.swing.JLabel();
        jLabel_fecha_lanzamiento = new javax.swing.JLabel();
        jLabel_saga_videojuego = new javax.swing.JLabel();
        jComboBox_saga = new javax.swing.JComboBox<>();
        jTextField_fecha_lanzamiento = new javax.swing.JTextField();
        jTextField_nombre_videojuego = new javax.swing.JTextField();
        jTextField_motor_videojuego = new javax.swing.JTextField();
        jButton_guardar_videojuego = new javax.swing.JButton();
        jButton_cancelar_videojuego = new javax.swing.JButton();
        jButton_borrar_videojuego = new javax.swing.JButton();
        jButton_modificar_videojuego = new javax.swing.JButton();
        jButton_aniadir_videojuego = new javax.swing.JButton();
        jLabel_pegi = new javax.swing.JLabel();
        jTextField_pegi = new javax.swing.JTextField();
        jPanel_personaje = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_personaje = new javax.swing.JTable();
        jLabel_nombre_personaje = new javax.swing.JLabel();
        jLabel_interprete_modelo = new javax.swing.JLabel();
        jLabel_interprete_voz = new javax.swing.JLabel();
        jLabel_videojuego_personaje = new javax.swing.JLabel();
        jComboBox_videojuego = new javax.swing.JComboBox<>();
        jTextField_interprete_voz = new javax.swing.JTextField();
        jTextField_nombre_personaje = new javax.swing.JTextField();
        jTextField_interprete_modelo = new javax.swing.JTextField();
        jButton_guardar_personaje = new javax.swing.JButton();
        jButton_cancelar_personaje = new javax.swing.JButton();
        jButton_borrar_personaje = new javax.swing.JButton();
        jButton_modificar_personaje = new javax.swing.JButton();
        jButton_aniadir_personaje = new javax.swing.JButton();
        jLabel_ano_primera_aparicion = new javax.swing.JLabel();
        jTextField_ano_primera_aparicion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                //formWindowClosing(evt);
            }
        });

        jPanel_empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_empresaMouseClicked(evt);
            }
        });

        jTable_empresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre empresa", "Pais sede"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_empresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_empresa);

        jButton_aniadir_empresa.setText("Añadir");
        jButton_aniadir_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aniadir_empresaActionPerformed(evt);
            }
        });

        jButton_modificar_empresa.setText("Modificar");
        jButton_modificar_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificar_empresaActionPerformed(evt);
            }
        });

        jButton_borrar_empresa.setText("Borrar");
        jButton_borrar_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrar_empresaActionPerformed(evt);
            }
        });

        jLabel_nombre_empresa.setText("Nombre empresa:");

        jLabel_pais_sede.setText("Pais sede:");

        jLabel_fecha_fundacion.setText("Fecha fundación:");

        jButton_guardar_empresa.setText("Guardar");
        jButton_guardar_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardar_empresaActionPerformed(evt);
            }
        });

        jButton_cancelar_empresa.setText("Cancelar");
        jButton_cancelar_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelar_empresaActionPerformed(evt);
            }
        });

        jLabel_director_ejecutivo.setText("ceo:");

        javax.swing.GroupLayout jPanel_empresaLayout = new javax.swing.GroupLayout(jPanel_empresa);
        jPanel_empresa.setLayout(jPanel_empresaLayout);
        jPanel_empresaLayout.setHorizontalGroup(
            jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_empresaLayout.createSequentialGroup()
                .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_empresaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombre_empresa)
                            .addComponent(jLabel_pais_sede)
                            .addComponent(jLabel_fecha_fundacion)
                            .addComponent(jLabel_director_ejecutivo))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_nombre_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField_pais_sede)
                            .addComponent(jTextField_fecha_fundacion)
                            .addComponent(jTextField_director_ejecutivo))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_guardar_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_cancelar_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                    .addGroup(jPanel_empresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_modificar_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_aniadir_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_borrar_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_empresaLayout.setVerticalGroup(
            jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_empresaLayout.createSequentialGroup()
                .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_empresaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton_aniadir_empresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_modificar_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_borrar_empresa))
                    .addGroup(jPanel_empresaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre_empresa)
                    .addComponent(jTextField_nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pais_sede)
                    .addComponent(jTextField_pais_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_guardar_empresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fecha_fundacion)
                    .addComponent(jTextField_fecha_fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancelar_empresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_director_ejecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_director_ejecutivo))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Empresa", jPanel_empresa);

        jTable_saga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre saga", "Desarrolladora", "Género"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_saga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_sagaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_saga);

        jLabel_nombre_saga.setText("Nombre saga:");

        jLabel_desarrolladora.setText("Desarrolladora:");

        jLabel_anio_creacion.setText("Año creación");

        jButton_guardar_saga.setText("Guardar");
        jButton_guardar_saga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardar_sagaActionPerformed(evt);
            }
        });

        jButton_cancelar_saga.setText("Cancelar");
        jButton_cancelar_saga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelar_sagaActionPerformed(evt);
            }
        });

        jButton_aniadir_saga.setText("Añadir");
        jButton_aniadir_saga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aniadir_sagaActionPerformed(evt);
            }
        });

        jButton_modificar_saga.setText("Modificar");
        jButton_modificar_saga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificar_sagaActionPerformed(evt);
            }
        });

        jButton_borrar_saga.setText("Borrar");
        jButton_borrar_saga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrar_sagaActionPerformed(evt);
            }
        });

        jComboBox_compania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jComboBox_companiaActionPerformed(evt);
            }
        });

        jLabel_compania_pertenece_saga.setText("Compañía");

        jLabel_genero.setText("Género:");

        javax.swing.GroupLayout jPanel_sagaLayout = new javax.swing.GroupLayout(jPanel_saga);
        jPanel_saga.setLayout(jPanel_sagaLayout);
        jPanel_sagaLayout.setHorizontalGroup(
            jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sagaLayout.createSequentialGroup()
                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sagaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_modificar_saga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_aniadir_saga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_borrar_saga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_sagaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombre_saga)
                            .addComponent(jLabel_desarrolladora)
                            .addComponent(jLabel_anio_creacion)
                            .addComponent(jLabel_compania_pertenece_saga)
                            .addComponent(jLabel_genero))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_compania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_sagaLayout.createSequentialGroup()
                                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_nombre_saga, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(jTextField_desarrolladora)
                                    .addComponent(jTextField_anio_creacion)
                                    .addComponent(jTextField_genero))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_guardar_saga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_cancelar_saga, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_sagaLayout.setVerticalGroup(
            jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sagaLayout.createSequentialGroup()
                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sagaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton_aniadir_saga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_modificar_saga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_borrar_saga))
                    .addGroup(jPanel_sagaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre_saga)
                    .addComponent(jTextField_nombre_saga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_desarrolladora)
                    .addComponent(jTextField_desarrolladora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_guardar_saga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_anio_creacion)
                    .addComponent(jTextField_anio_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancelar_saga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_genero)
                    .addComponent(jTextField_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel_sagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_compania_pertenece_saga)
                    .addComponent(jComboBox_compania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Saga", jPanel_saga);

        jTable_videojuego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre videojuego", "Motor videojuego", "Fecha lanzamiento", "PEGI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_videojuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_videojuegoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_videojuego);

        jLabel_nombre_videojuego.setText("Nombre videojuego:");

        jLabel_motor_videojuego.setText("Motor videojuego:");

        jLabel_fecha_lanzamiento.setText("Fecha lanzamiento :");

        jLabel_saga_videojuego.setText("Saga:");

        jComboBox_saga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jComboBox_sagaActionPerformed(evt);
            }
        });

        jButton_guardar_videojuego.setText("Guardar");
        jButton_guardar_videojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardar_videojuegoActionPerformed(evt);
            }
        });

        jButton_cancelar_videojuego.setText("Cancelar");
        jButton_cancelar_videojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelar_videojuegoActionPerformed(evt);
            }
        });

        jButton_borrar_videojuego.setText("Borrar");
        jButton_borrar_videojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrar_videojuegoActionPerformed(evt);
            }
        });

        jButton_modificar_videojuego.setText("Modificar");
        jButton_modificar_videojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificar_videojuegoActionPerformed(evt);
            }
        });

        jButton_aniadir_videojuego.setText("Añadir");
        jButton_aniadir_videojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aniadir_videojuegoActionPerformed(evt);
            }
        });

        jLabel_pegi.setText("PEGI:");

        javax.swing.GroupLayout jPanel_videojuegoLayout = new javax.swing.GroupLayout(jPanel_videojuego);
        jPanel_videojuego.setLayout(jPanel_videojuegoLayout);
        jPanel_videojuegoLayout.setHorizontalGroup(
            jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_videojuegoLayout.createSequentialGroup()
                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_videojuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_modificar_videojuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_aniadir_videojuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_borrar_videojuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_videojuegoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombre_videojuego)
                            .addComponent(jLabel_motor_videojuego)
                            .addComponent(jLabel_fecha_lanzamiento)
                            .addComponent(jLabel_saga_videojuego)
                            .addComponent(jLabel_pegi))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_saga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_videojuegoLayout.createSequentialGroup()
                                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_pegi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_nombre_videojuego, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(jTextField_motor_videojuego, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_fecha_lanzamiento, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_guardar_videojuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_cancelar_videojuego, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_videojuegoLayout.setVerticalGroup(
            jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_videojuegoLayout.createSequentialGroup()
                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_videojuegoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton_aniadir_videojuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_modificar_videojuego, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_borrar_videojuego))
                    .addGroup(jPanel_videojuegoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre_videojuego)
                    .addComponent(jTextField_nombre_videojuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_motor_videojuego)
                    .addComponent(jTextField_motor_videojuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_guardar_videojuego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fecha_lanzamiento)
                    .addComponent(jTextField_fecha_lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancelar_videojuego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pegi)
                    .addComponent(jTextField_pegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_videojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_saga_videojuego)
                    .addComponent(jComboBox_saga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Videojuego", jPanel_videojuego);

        jTable_personaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre personaje", "Año primera aparición"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_personaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_personajeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable_personaje);

        jLabel_nombre_personaje.setText("Nombre personaje:");

        jLabel_interprete_modelo.setText("Intérprete modelo:");

        jLabel_interprete_voz.setText("Intérprete voz:");

        jLabel_videojuego_personaje.setText("Videojuego:");

        jComboBox_videojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jComboBox_videojuegoActionPerformed(evt);
            }
        });

        jButton_guardar_personaje.setText("Guardar");
        jButton_guardar_personaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardar_personajeActionPerformed(evt);
            }
        });

        jButton_cancelar_personaje.setText("Cancelar");
        jButton_cancelar_personaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelar_personajeActionPerformed(evt);
            }
        });

        jButton_borrar_personaje.setText("Borrar");
        jButton_borrar_personaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrar_personajeActionPerformed(evt);
            }
        });

        jButton_modificar_personaje.setText("Modificar");
        jButton_modificar_personaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificar_personajeActionPerformed(evt);
            }
        });

        jButton_aniadir_personaje.setText("Añadir");
        jButton_aniadir_personaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aniadir_personajeActionPerformed(evt);
            }
        });

        jLabel_ano_primera_aparicion.setText("Año primera aparición:");

        javax.swing.GroupLayout jPanel_personajeLayout = new javax.swing.GroupLayout(jPanel_personaje);
        jPanel_personaje.setLayout(jPanel_personajeLayout);
        jPanel_personajeLayout.setHorizontalGroup(
            jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_personajeLayout.createSequentialGroup()
                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_personajeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_modificar_personaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_aniadir_personaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_borrar_personaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_personajeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombre_personaje)
                            .addComponent(jLabel_interprete_modelo)
                            .addComponent(jLabel_interprete_voz)
                            .addComponent(jLabel_videojuego_personaje)
                            .addComponent(jLabel_ano_primera_aparicion))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_videojuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_personajeLayout.createSequentialGroup()
                                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_nombre_personaje, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(jTextField_interprete_modelo)
                                    .addComponent(jTextField_interprete_voz)
                                    .addComponent(jTextField_ano_primera_aparicion, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_guardar_personaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_cancelar_personaje, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_personajeLayout.setVerticalGroup(
            jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_personajeLayout.createSequentialGroup()
                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_personajeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton_aniadir_personaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_modificar_personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_borrar_personaje))
                    .addGroup(jPanel_personajeLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre_personaje)
                    .addComponent(jTextField_nombre_personaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_interprete_modelo)
                    .addComponent(jTextField_interprete_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_guardar_personaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_interprete_voz)
                    .addComponent(jTextField_interprete_voz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancelar_personaje))
                .addGap(18, 18, 18)
                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ano_primera_aparicion)
                    .addComponent(jTextField_ano_primera_aparicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel_personajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_videojuego_personaje)
                    .addComponent(jComboBox_videojuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Personaje", jPanel_personaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("Ciudad");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CargarArraysDeDatos(){
        
        this.listaEmpresas.removeAll(this.listaEmpresas);
        this.listaSagas.removeAll(listaSagas);
        this.listaVideojuegos.removeAll(listaVideojuegos);
        this.listaPersonajes.removeAll(listaPersonajes);
        
        leerFichero.LeerFicheroEmpresa(listaEmpresas);
        leerFichero.LeerFicheroSaga(listaSagas);
        leerFichero.LeerFicheroVideojuego(listaVideojuegos);
        leerFichero.LeerFicheroPersonaje(listaPersonajes);
    }
    
    private void CargarDatosPersonajeEnVista(){
        
        CambiarEdiccionPersonaje(false);
        jButton_modificar_personaje.setEnabled(false);
        MostrarTablaPersonaje();
        seleccionar = -1;
    }
    private void jPanel_personajeMouseClicked(java.awt.event.MouseEvent evt) {
        
        MeterVideojuegoComboBox();
        this.CargarDatosPersonajeEnVista();
        seleccionar = -1;
    }
    private void jButton_modificar_personajeActionPerformed(java.awt.event.ActionEvent evt){
        
        CambiarEdiccionPersonaje(true);
    }
    private void jButton_borrar_personajeActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoPersonajeTextfield();
        BorrarPersonajeDelArray();
    }
    
    private void BorrarPersonajeDelArray(){
        
        this.listaPersonajes.remove(seleccionar);
        MostrarTablaPersonaje();
        crearFichero.EscribirFicheroPersonajes(this.listaPersonajes);
    }
    private void jTable_personajeMouseClicked(java.awt.event.MouseEvent evt){

        String nombreVideojuego = null;
        int i = 0;
        seleccionar = jTable_personaje.rowAtPoint(evt.getPoint());
        jTextField_nombre_personaje.setText(String.valueOf(listaPersonajes.get(seleccionar).getNombreProtagonista()));
        jTextField_interprete_modelo.setText(String.valueOf(listaPersonajes.get(seleccionar).getInterpreteModelo()));
        jTextField_interprete_voz.setText(String.valueOf(listaPersonajes.get(seleccionar).getInterpreteVoz()));
        jTextField_ano_primera_aparicion.setText(String.valueOf(listaPersonajes.get(seleccionar).getAnioAparicion()));
        for(i = 0; i < this.listaVideojuegos.size(); i++){
            if(this.listaVideojuegos.get(i).getIdVideojuego() == this.listaPersonajes.get(seleccionar).getIdVideojuegoPertenece()){
                nombreVideojuego = this.listaVideojuegos.get(i).getNombreVideojuego();
            }
        }
        for(i = 0; i < this.jComboBox_videojuego.getComponentCount(); i++){
            if(this.jComboBox_videojuego.getItemAt(i).equals(nombreVideojuego)){
                jComboBox_videojuego.setSelectedIndex(i);
            }
        }
        jButton_modificar_personaje.setEnabled(true);
    }
    
    private void MostrarTablaPersonaje(){
        
        String matriz [][] = new String [listaPersonajes.size()][2];
        
        for(int i = 0; i < listaPersonajes.size(); i++){
            
            matriz[i][0] = listaPersonajes.get(i).getNombreProtagonista();
            matriz[i][1] = String.valueOf(listaPersonajes.get(i).getAnioAparicion());
        }
        
        jTable_personaje.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre personaje", "Año primera aparición"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    private void ExtraerDatosPersonaje(){
        
        String nombrePersonaje = jTextField_nombre_personaje.getText();
        String interpreteModelo = jTextField_interprete_modelo.getText();
        String interpreteVoz = jTextField_interprete_voz.getText();
        int primeraAparicion = Integer.parseInt(jTextField_ano_primera_aparicion.getText());
        int id = 0;
        if(this.listaPersonajes.size() != 0){
            id = this.listaPersonajes.get(this.listaPersonajes.size()-1).getIdProtagonista()+1;
        }
        int idVideojuego = -1;
        for(int i = 0; i < listaVideojuegos.size(); i++){
            
            if(listaVideojuegos.get(i).getNombreVideojuego().equals(jComboBox_videojuego.getSelectedItem())){
                
                idVideojuego = listaVideojuegos.get(i).getIdVideojuego();
            }    
        }
        
        Personaje personajeAñadido = new Personaje(nombrePersonaje, interpreteModelo, interpreteVoz, primeraAparicion, id, idVideojuego);
        listaPersonajes.add(personajeAñadido);
        BorrarTextoVideojuegoTextfield();
    }
    
    private void jButton_aniadir_personajeActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoPersonajeTextfield();
        CambiarEdiccionPersonaje(true);
    }
    
    private void jButton_cancelar_personajeActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoPersonajeTextfield();
        CambiarEdiccionPersonaje(false);
        seleccionar = -1;
        this.CargarDatosPersonajeEnVista();
    }
    
    private void BorrarTextoPersonajeTextfield(){
        
       jTextField_nombre_personaje.setText(null); 
       jTextField_interprete_modelo.setText(null);
       jTextField_interprete_voz.setText(null);
       jTextField_ano_primera_aparicion.setText(null);
    }
    
    private void ModificarDelArrayPersonajes(){
        
        String nombrePersonaje = jTextField_nombre_personaje.getText();
        String interpreteModelo = jTextField_interprete_modelo.getText();
        String interpreteVoz = jTextField_interprete_voz.getText();
        String anoPrimeraAparicion = jTextField_ano_primera_aparicion.getText();
        String videojuegoPertenece = (String)jComboBox_videojuego.getSelectedItem();
        int id = -1;
        int i = 0;
        for(i = 0; i < listaVideojuegos.size(); i++){
            
            if(listaVideojuegos.get(i).getNombreVideojuego().equals(videojuegoPertenece))
                id = listaVideojuegos.get(i).getIdVideojuego();
        }
        
        for(i = 0; i < listaPersonajes.size(); i++){
            
            if(listaPersonajes.get(i).getNombreProtagonista().equals(this.listaPersonajes.get(seleccionar).getNombreProtagonista())){
                
                listaPersonajes.get(i).setNombreProtagonista(nombrePersonaje);
                listaPersonajes.get(i).setInterpreteModelo(interpreteModelo);
                listaPersonajes.get(i).setInterpreteVoz(interpreteVoz);
                listaPersonajes.get(i).setAnioAparicion(Integer.parseInt(anoPrimeraAparicion));
                listaPersonajes.get(i).setIdVideojuegoPertenece(id);
            }
        }
    }
    
    private void jButton_guardar_personajeActionPerformed(java.awt.event.ActionEvent evt){
        
        if (seleccionar != -1){
            
            ModificarDelArrayPersonajes();
            seleccionar = -1;
        }
        else{
            ExtraerDatosPersonaje();
        }
        
        BorrarTextoPersonajeTextfield();
        CambiarEdiccionPersonaje(false);
        MostrarTablaPersonaje();
        this.crearFichero.EscribirFicheroPersonajes(listaPersonajes);
        seleccionar = -1;
        this.CargarDatosPersonajeEnVista();
    }
    
    private void CambiarEdiccionPersonaje(boolean sino){
        
       jTextField_nombre_personaje.setEditable(sino); 
       jTextField_interprete_modelo.setEditable(sino);
       jTextField_interprete_voz.setEditable(sino);
       jTextField_ano_primera_aparicion.setEditable(sino);
       this.jComboBox_videojuego.setEnabled(sino);
       this.jButton_guardar_personaje.setEnabled(sino);
    }
    
    //Parte del panelVideojuego.
    private void MeterVideojuegoComboBox(){
        
        jComboBox_videojuego.removeAllItems();
        for(int i = 0; i < listaVideojuegos.size(); i++){
            
            jComboBox_videojuego.addItem(listaVideojuegos.get(i).getNombreVideojuego());
        }
    }
    private void CargarDatosVideojuegoEnVista(){
        
        CambiarEdiccionVideojuego(false);
        jButton_modificar_videojuego.setEnabled(false);
        MostrarTablaVideojuego();
        this.MeterVideojuegoComboBox();
        seleccionar = -1;
    }
    private void jPanel_videojuegoMouseClicked(java.awt.event.MouseEvent evt) {
        
        this.CargarDatosVideojuegoEnVista();
        MeterSagaComboBox();
        seleccionar = -1;
    }
    private void jButton_modificar_videojuegoActionPerformed(java.awt.event.ActionEvent evt){
        
        CambiarEdiccionVideojuego(true);
    }
    private void jButton_borrar_videojuegoActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoVideojuegoTextfield();
        BorrarVideojuegoDelArray();
        MeterVideojuegoComboBox();
    }
    
    private void BorrarVideojuegoDelArray(){
        
        boolean posibilidadBorrado = true;
        for(int i = 0; i < listaPersonajes.size(); i++){
            if(listaPersonajes.get(i).getIdVideojuegoPertenece() == listaVideojuegos.get(seleccionar).getIdVideojuego()){
                JOptionPane.showConfirmDialog(null, "Imposible de borrar mientras haya un personaje relacionado.");
                posibilidadBorrado = false;
            }
        }
        if(posibilidadBorrado){
            this.listaVideojuegos.remove(seleccionar);
            MostrarTablaVideojuego();
            MeterVideojuegoComboBox();
            CargarDatosPersonajeEnVista();
            crearFichero.EscribirFicheroVideojuegos(this.listaVideojuegos);
        }
    }
    private void jTable_videojuegoMouseClicked(java.awt.event.MouseEvent evt){

        String nombreSaga = null;
        int i = -1;
        seleccionar = jTable_videojuego.rowAtPoint(evt.getPoint());
        jTextField_nombre_videojuego.setText(String.valueOf(listaVideojuegos.get(seleccionar).getNombreVideojuego()));
        jTextField_motor_videojuego.setText(String.valueOf(listaVideojuegos.get(seleccionar).getMotorVideojuego()));
        jTextField_fecha_lanzamiento.setText(String.valueOf(listaVideojuegos.get(seleccionar).getFechaLanzamiento()));
        jTextField_pegi.setText(String.valueOf(listaVideojuegos.get(seleccionar).getPegi()));
        
        for(i = 0; i < this.listaSagas.size(); i++){
            if(this.listaSagas.get(i).getIdSaga() == this.listaVideojuegos.get(seleccionar).getIdSagaVideojuego()){
                nombreSaga = this.listaSagas.get(i).getNombreSaga();
            }
        }
        for (i = 0; i < this.jComboBox_saga.getComponentCount(); i++){
            if(this.jComboBox_saga.getItemAt(i).equals(nombreSaga)){
                this.jComboBox_saga.setSelectedIndex(i);
            }
        }
        jButton_modificar_videojuego.setEnabled(true);
    }
    
    private void MostrarTablaVideojuego(){
        
        String matriz [][] = new String [listaVideojuegos.size()][4];
        
        for(int i = 0; i < listaVideojuegos.size(); i++){
            
            matriz[i][0] = listaVideojuegos.get(i).getNombreVideojuego();
            matriz[i][1] = listaVideojuegos.get(i).getMotorVideojuego();
            matriz[i][2] = listaVideojuegos.get(i).getFechaLanzamiento();
            matriz[i][3] = String.valueOf(listaVideojuegos.get(i).getPegi());
        }
        
        jTable_videojuego.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre videojuego", "Motor videojuego", "Fecha lanzamiento", "pegi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    private void ExtraerDatosVideojuego(){
        
        String nombreVideojuego = jTextField_nombre_videojuego.getText();
        String motorVideojuego = jTextField_motor_videojuego.getText();
        String fechaLanzamiento = jTextField_fecha_lanzamiento.getText();
        int pegi = Integer.parseInt(jTextField_pegi.getText());
        int id = 0;
        if(this.listaVideojuegos.size()!=0){
            id = this.listaVideojuegos.get(this.listaVideojuegos.size()-1).getIdVideojuego() +1;
        }
        int idSaga = -1; 
        for(int i = 0; i < listaSagas.size(); i++){
            
            if(listaSagas.get(i).getNombreSaga().equals(jComboBox_saga.getSelectedItem())){
                
                idSaga = listaSagas.get(i).getIdSaga();
            }    
        }
        
        Videojuego videojuegoAñadido = new Videojuego(nombreVideojuego, motorVideojuego, fechaLanzamiento, pegi, id, idSaga);
        listaVideojuegos.add(videojuegoAñadido);
        BorrarTextoVideojuegoTextfield();
    }
    
    private void jButton_aniadir_videojuegoActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoVideojuegoTextfield();
        CambiarEdiccionVideojuego(true);
    }
    
    private void jButton_cancelar_videojuegoActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoVideojuegoTextfield();
        CambiarEdiccionVideojuego(false);
        seleccionar = -1;
        this.CargarDatosVideojuegoEnVista();
    }
    
    private void BorrarTextoVideojuegoTextfield(){
        
       jTextField_nombre_videojuego.setText(null); 
       jTextField_motor_videojuego.setText(null);
       jTextField_fecha_lanzamiento.setText(null);
       jTextField_pegi.setText(null);
    }
    
    private void ModificarDelArrayVideojuegos(){
        
        String nombreVideojuego = jTextField_nombre_videojuego.getText();
        String motorVideojuego = jTextField_motor_videojuego.getText();
        String fechaLanzamiento = jTextField_fecha_lanzamiento.getText();
        String pegi = jTextField_pegi.getText();
        String sagaPertenece = (String) jComboBox_saga.getSelectedItem();
        int id = -1;
        int i = 0;
        for(i = 0; i < listaSagas.size(); i++){
            
            if(listaSagas.get(i).getNombreSaga().equals(sagaPertenece))
                id = listaSagas.get(i).getIdSaga();
        }
        
        for(i = 0; i < listaVideojuegos.size(); i++){
            
            if(listaVideojuegos.get(i).getNombreVideojuego().equals(this.listaVideojuegos.get(seleccionar).getNombreVideojuego())){
                
                listaVideojuegos.get(i).setNombreVideojuego(nombreVideojuego);
                listaVideojuegos.get(i).setMotorVideojuego(motorVideojuego);
                listaVideojuegos.get(i).setFechaLanzamiento(fechaLanzamiento);
                listaVideojuegos.get(i).setPegi(Integer.parseInt(pegi));
                listaVideojuegos.get(i).setIdSagaVideojuego(id);
            }
        }
    }
    
    private void jButton_guardar_videojuegoActionPerformed(java.awt.event.ActionEvent evt){
        
        if (seleccionar != -1){
            
            ModificarDelArrayVideojuegos();
            this.seleccionar = -1;
        }
        else{
           ExtraerDatosVideojuego();
           MeterVideojuegoComboBox();
        }
        
        BorrarTextoVideojuegoTextfield();
        CambiarEdiccionVideojuego(false);
        MostrarTablaVideojuego();
        this.crearFichero.EscribirFicheroVideojuegos(listaVideojuegos);
        seleccionar = -1;
        this.CargarDatosVideojuegoEnVista();
    }
    
    private void CambiarEdiccionVideojuego(boolean sino){
        
       jTextField_nombre_videojuego.setEditable(sino); 
       jTextField_motor_videojuego.setEditable(sino);
       jTextField_fecha_lanzamiento.setEditable(sino);
       jTextField_pegi.setEditable(sino);
       this.jComboBox_saga.setEnabled(sino);
       this.jButton_guardar_videojuego.setEnabled(sino);
    }
    
    //Parte del panelSaga.
    
    private void MeterSagaComboBox(){
        
        jComboBox_saga.removeAllItems();
        for(int i = 0; i < listaSagas.size(); i++){
            
            jComboBox_saga.addItem(listaSagas.get(i).getNombreSaga());
        }
    }
    private void CargarDatosSagaEnVista(){
        
        CambiarEdiccionSaga(false);
        jButton_modificar_saga.setEnabled(false);
        MostrarTablaSaga();
        this.MeterSagaComboBox();
        seleccionar = -1;
    }
    private void jPanel_sagaMouseClicked(java.awt.event.MouseEvent evt) {
        
        CargarDatosSagaEnVista();
        MeterEmpresaComboBox();
        seleccionar = -1;
    }
    private void jButton_modificar_sagaActionPerformed(java.awt.event.ActionEvent evt){
        
        CambiarEdiccionSaga(true);
    }
    private void jButton_borrar_sagaActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoSagaTextfield();
        BorrarSagaDelArray();
        MeterSagaComboBox();
    }
    
    private void BorrarSagaDelArray(){
        
        boolean posibilidadBorrado = true;
        for(int i = 0; i < listaVideojuegos.size(); i++){
            if(listaVideojuegos.get(i).getIdSagaVideojuego() == listaSagas.get(seleccionar).getIdSaga()){
                JOptionPane.showConfirmDialog(null, "Imposible de borrar mientras haya un videojuego relacionado.");
                posibilidadBorrado = false;
            }
        }
        if(posibilidadBorrado){
            this.listaSagas.remove(seleccionar);
            MostrarTablaSaga();
            MeterSagaComboBox();
            CargarDatosVideojuegoEnVista();
            crearFichero.EscribirFicheroSagas(this.listaSagas);
        }
    }
    private void jTable_sagaMouseClicked(java.awt.event.MouseEvent evt){

        String nombreEmpresa = null;
        int i = -1;
        seleccionar = jTable_saga.rowAtPoint(evt.getPoint());
        jTextField_nombre_saga.setText(String.valueOf(listaSagas.get(seleccionar).getNombreSaga()));
        jTextField_desarrolladora.setText(String.valueOf(listaSagas.get(seleccionar).getDesarrolladora()));
        jTextField_anio_creacion.setText(String.valueOf(listaSagas.get(seleccionar).getAnioCreacion()));
        jTextField_genero.setText(String.valueOf(listaSagas.get(seleccionar).getGenero()));
        
        for(i = 0; i < listaEmpresas.size(); i++){
            
            if(listaEmpresas.get(i).getIdEmpresa() == listaSagas.get(seleccionar).getIDEmpresaAsignadaSaga()){
                
                nombreEmpresa = listaEmpresas.get(i).getNombre();
                
            }
        }
        //TODO: Error con los combobox.
        for(i = 0; i < jComboBox_compania.getComponentCount(); i++){
            
            if(jComboBox_compania.getItemAt(i).equals(nombreEmpresa)){
                 jComboBox_compania.setSelectedIndex(i);
            }
        }
        jButton_modificar_saga.setEnabled(true);
    }
    
    private void MostrarTablaSaga(){
        
        String matriz [][] = new String [listaSagas.size()][3];
        
        for(int i = 0; i < listaSagas.size(); i++){
            
            matriz[i][0] = listaSagas.get(i).getNombreSaga();
            matriz[i][1] = listaSagas.get(i).getDesarrolladora();
            matriz[i][2] = listaSagas.get(i).getGenero();
        }
        
        jTable_saga.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre saga", "Desarrolladora", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    private void ExtraerDatosSaga(){
        
        String nombreSaga = jTextField_nombre_saga.getText();
        String desarrolladora = jTextField_desarrolladora.getText();
        int anio_creacion = Integer.parseInt(jTextField_anio_creacion.getText());
        String genero = jTextField_genero.getText();
        int id = 0;
        if(listaSagas.size() != 0)
            id = listaSagas.get(this.listaSagas.size()-1).getIdSaga() + 1;       
        int idEmpresa = -1; 
        for(int i = 0; i < listaEmpresas.size(); i++){
            
            if(listaEmpresas.get(i).getNombre().equals(jComboBox_compania.getSelectedItem())){
                
                idEmpresa = listaEmpresas.get(i).getIdEmpresa();
            }    
        }
        
        Saga sagaAñadida = new Saga(nombreSaga, desarrolladora, genero, anio_creacion, id, idEmpresa);
        listaSagas.add(sagaAñadida);
        BorrarTextoSagaTextfield();
    }
    
    private void jButton_aniadir_sagaActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoSagaTextfield();
        CambiarEdiccionSaga(true);
    }
    
    private void jButton_cancelar_sagaActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoSagaTextfield();
        CambiarEdiccionSaga(false);
        seleccionar = -1;
        CargarDatosSagaEnVista();
    }
    
    private void BorrarTextoSagaTextfield(){
        
       jTextField_nombre_saga.setText(null); 
       jTextField_desarrolladora.setText(null);
       jTextField_anio_creacion.setText(null);
       jTextField_genero.setText(null);
    }
    
    private void ModificarDelArraySagas(){
        
        String nombreSaga = jTextField_nombre_saga.getText();
        String desarrolladora = jTextField_desarrolladora.getText();
        String anioCreacion = jTextField_anio_creacion.getText();
        String genero = jTextField_genero.getText();
        String empresaPertenece = (String) jComboBox_compania.getSelectedItem();
        int id = -1;
        int i = 0;
        for(i = 0; i < listaEmpresas.size(); i++){
            
            if(listaEmpresas.get(i).getNombre().equals(empresaPertenece))
                id = listaEmpresas.get(i).getIdEmpresa();
        }
        
        for(i = 0; i < listaSagas.size(); i++){
            
            if(listaSagas.get(i).getNombreSaga().equals(listaSagas.get(seleccionar).getNombreSaga())){
                
                listaSagas.get(i).setNombreSaga(nombreSaga);
                listaSagas.get(i).setDesarrolladora(desarrolladora);
                listaSagas.get(i).setAnioCreacion(Integer.parseInt(anioCreacion));
                listaSagas.get(i).setGenero(genero);
                listaSagas.get(i).setIDEmpresaAsignadaSaga(id);
            }
        }
    }
    
    private void jButton_guardar_sagaActionPerformed(java.awt.event.ActionEvent evt){
        
        if (seleccionar != -1){
            
            ModificarDelArraySagas();
            seleccionar = -1;
        }
        else{
          ExtraerDatosSaga();
          MeterSagaComboBox();
        }
        BorrarTextoSagaTextfield();
        CambiarEdiccionSaga(false);
        MostrarTablaSaga();
        crearFichero.EscribirFicheroSagas(listaSagas);
        seleccionar = -1;
        CargarDatosSagaEnVista();
    }
    
    private void CambiarEdiccionSaga(boolean sino){
        
       jTextField_nombre_saga.setEditable(sino); 
       jTextField_desarrolladora.setEditable(sino);
       jTextField_anio_creacion.setEditable(sino);
       jTextField_genero.setEditable(sino);
       jComboBox_compania.setEnabled(sino);
       this.jButton_guardar_saga.setEnabled(sino);
    }
    
    //Parte del panelEmpresa.
    
    private void MeterEmpresaComboBox(){
        
        jComboBox_compania.removeAllItems();
        for(int i = 0; i < listaEmpresas.size(); i++){
            
            jComboBox_compania.addItem(listaEmpresas.get(i).getNombre());
        }
    }
    
    private void jPanel_empresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_empresaMouseClicked
        
        CargarDatosEmpresaEnVista();
    }//GEN-LAST:event_jPanel_empresaMouseClicked
  
    private void CargarDatosEmpresaEnVista(){
        
        CambiarEdiccionEmpresa(false);
        jButton_modificar_empresa.setEnabled(false);
        MeterEmpresaComboBox();
        MostrarTablaEmpresa();
        seleccionar = -1;
    }
    private void jButton_modificar_empresaActionPerformed(java.awt.event.ActionEvent evt){
        
        CambiarEdiccionEmpresa(true);
    }
    private void jButton_borrar_empresaActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoEmpresaTextfield();
        BorrarEmpresaDelArray();
        this.seleccionar = -1;
    }

    private void BorrarEmpresaDelArray(){
        
        boolean posibilidadBorrado = true;
        for(int i = 0; i < listaSagas.size(); i++){
            if(listaSagas.get(i).getIDEmpresaAsignadaSaga() == listaEmpresas.get(seleccionar).getIdEmpresa()){
                JOptionPane.showMessageDialog(null, "Imposible de borrar mientras haya una saga relacionada.", "Error", JOptionPane.OK_CANCEL_OPTION);
                posibilidadBorrado = false;
            }
        }
        if(posibilidadBorrado){
            this.listaEmpresas.remove(seleccionar);
            MostrarTablaEmpresa();
            MeterEmpresaComboBox();
            CargarDatosEmpresaEnVista();
            seleccionar = -1;
            crearFichero.EscribirFicheroEmpresas(listaEmpresas);
        }
    }
    private void jTable_empresaMouseClicked(java.awt.event.MouseEvent evt){

        seleccionar = jTable_empresa.rowAtPoint(evt.getPoint());
        
        for(int i = 0; i < listaEmpresas.size(); i++){
           if(listaEmpresas.get(i).getNombre().equals(jTable_empresa.getValueAt(seleccionar, 1)))
              seleccionar = listaEmpresas.get(i).getIdEmpresa();
        }
        
        jTextField_nombre_empresa.setText(listaEmpresas.get(seleccionar).getNombre());
        jTextField_pais_sede.setText(listaEmpresas.get(seleccionar).getPaisSede());
        jTextField_fecha_fundacion.setText(listaEmpresas.get(seleccionar).getFechaFundacion());
        jTextField_director_ejecutivo.setText(listaEmpresas.get(seleccionar).getCeo());
        jButton_modificar_empresa.setEnabled(true);
    }
    
    private void MostrarTablaEmpresa(){
        
        String matriz [][] = new String [listaEmpresas.size()][2];
        
        for(int i = 0; i < listaEmpresas.size(); i++){
            
            matriz[i][0] = listaEmpresas.get(i).getNombre();
            matriz[i][1] = listaEmpresas.get(i).getPaisSede();
        }
        
        jTable_empresa.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre empresa", "Pais sede"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    private void ExtraerDatosEmpresa(){
        
        String nombreEmpresa = jTextField_nombre_empresa.getText();
        String paisSede = jTextField_pais_sede.getText();
        String fechaFundacion = jTextField_fecha_fundacion.getText();
        String ceo = jTextField_director_ejecutivo.getText();
        int id = 0;
        if(this.listaEmpresas.size() != 0){
            id = listaEmpresas.get(this.listaEmpresas.size()-1).getIdEmpresa() + 1;
        }
        
        Empresa empresaAñadida = new Empresa(nombreEmpresa, paisSede, ceo, fechaFundacion, id);
        listaEmpresas.add(empresaAñadida);
        BorrarTextoEmpresaTextfield();
    }
    
    private void jButton_aniadir_empresaActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoEmpresaTextfield();
        CambiarEdiccionEmpresa(true);
    }
    
    private void jButton_cancelar_empresaActionPerformed(java.awt.event.ActionEvent evt){
        
        BorrarTextoEmpresaTextfield();
        CambiarEdiccionEmpresa(false);
        CargarDatosEmpresaEnVista();
    }
    
    private void BorrarTextoEmpresaTextfield(){
        
        jTextField_nombre_empresa.setText(null);       
        jTextField_pais_sede.setText(null);       
        jTextField_fecha_fundacion.setText(null);        
        jTextField_director_ejecutivo.setText(null);
    }
    
    private void ModificarDelArrayEmpresas(){
        
        String nombreEmpresa = jTextField_nombre_empresa.getText();
        String paisSede = jTextField_pais_sede.getText();
        String fechaFundacion = jTextField_fecha_fundacion.getText();
        String ceo = jTextField_director_ejecutivo.getText();
        this.ModificarSeleccionadoDelArray(nombreEmpresa, paisSede, fechaFundacion, ceo, seleccionar);
    }
    public void ModificarSeleccionadoDelArray(String nombre, String pais, String fecha, String ceo, int selector){
        
        for(int i = 0; i < listaEmpresas.size(); i++){
            
            if(listaEmpresas.get(i).getNombre().equals(listaEmpresas.get(selector).getNombre())){
                
                listaEmpresas.get(i).setNombre(nombre);
                listaEmpresas.get(i).setPaisSede(pais);
                listaEmpresas.get(i).setFechaFundacion(fecha);
                listaEmpresas.get(i).setCeo(ceo);
            }
        }
    }
    private void jButton_guardar_empresaActionPerformed(java.awt.event.ActionEvent evt){

            if (seleccionar != -1){

                ModificarDelArrayEmpresas();
                seleccionar = -1;
            }
            else{
                ExtraerDatosEmpresa();
                MeterEmpresaComboBox();
            }
        BorrarTextoEmpresaTextfield();
        CambiarEdiccionEmpresa(false);
        MostrarTablaEmpresa();
        crearFichero.EscribirFicheroEmpresas(listaEmpresas);
        CargarDatosEmpresaEnVista();
    }
    
    private void CambiarEdiccionEmpresa(boolean sino){
        
       jTextField_nombre_empresa.setEditable(sino); 
       jTextField_pais_sede.setEditable(sino);
       jTextField_fecha_fundacion.setEditable(sino);
       jTextField_director_ejecutivo.setEditable(sino);
       this.jButton_guardar_empresa.setEnabled(sino);
    }

    public ArrayList<Empresa> getListaEmpresas() {
        return listaEmpresas;
    }

    public void setListaEmpresas(ArrayList<Empresa> listaEmpresas) {
        this.listaEmpresas = listaEmpresas;
    }

    public EscribirMongoDB getCrearFichero() {
        return crearFichero;
    }
    
    public static void main(String args[]) {

                new Ventana().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aniadir_empresa;
    public javax.swing.JButton jButton_aniadir_personaje;
    private javax.swing.JButton jButton_aniadir_saga;
    private javax.swing.JButton jButton_aniadir_videojuego;
    private javax.swing.JButton jButton_borrar_empresa;
    public javax.swing.JButton jButton_borrar_personaje;
    private javax.swing.JButton jButton_borrar_saga;
    private javax.swing.JButton jButton_borrar_videojuego;
    private javax.swing.JButton jButton_cancelar_empresa;
    private javax.swing.JButton jButton_cancelar_personaje;
    private javax.swing.JButton jButton_cancelar_saga;
    public javax.swing.JButton jButton_cancelar_videojuego;
    private javax.swing.JButton jButton_guardar_empresa;
    private javax.swing.JButton jButton_guardar_personaje;
    private javax.swing.JButton jButton_guardar_saga;
    public javax.swing.JButton jButton_guardar_videojuego;
    private javax.swing.JButton jButton_modificar_empresa;
    public javax.swing.JButton jButton_modificar_personaje;
    private javax.swing.JButton jButton_modificar_saga;
    private javax.swing.JButton jButton_modificar_videojuego;
    public javax.swing.JComboBox<String> jComboBox_compania;
    public javax.swing.JComboBox<String> jComboBox_saga;
    private javax.swing.JComboBox<String> jComboBox_videojuego;
    private javax.swing.JLabel jLabel_anio_creacion;
    private javax.swing.JLabel jLabel_ano_primera_aparicion;
    private javax.swing.JLabel jLabel_compania_pertenece_saga;
    private javax.swing.JLabel jLabel_desarrolladora;
    private javax.swing.JLabel jLabel_director_ejecutivo;
    private javax.swing.JLabel jLabel_fecha_fundacion;
    private javax.swing.JLabel jLabel_fecha_lanzamiento;
    private javax.swing.JLabel jLabel_genero;
    private javax.swing.JLabel jLabel_interprete_modelo;
    private javax.swing.JLabel jLabel_interprete_voz;
    private javax.swing.JLabel jLabel_motor_videojuego;
    private javax.swing.JLabel jLabel_nombre_empresa;
    private javax.swing.JLabel jLabel_nombre_personaje;
    private javax.swing.JLabel jLabel_nombre_saga;
    private javax.swing.JLabel jLabel_nombre_videojuego;
    private javax.swing.JLabel jLabel_pais_sede;
    private javax.swing.JLabel jLabel_pegi;
    private javax.swing.JLabel jLabel_saga_videojuego;
    private javax.swing.JLabel jLabel_videojuego_personaje;
    private javax.swing.JPanel jPanel_empresa;
    private javax.swing.JPanel jPanel_personaje;
    private javax.swing.JPanel jPanel_saga;
    private javax.swing.JPanel jPanel_videojuego;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable_empresa;
    public javax.swing.JTable jTable_personaje;
    private javax.swing.JTable jTable_saga;
    private javax.swing.JTable jTable_videojuego;
    public javax.swing.JTextField jTextField_anio_creacion;
    private javax.swing.JTextField jTextField_ano_primera_aparicion;
    public javax.swing.JTextField jTextField_desarrolladora;
    public javax.swing.JTextField jTextField_director_ejecutivo;
    public javax.swing.JTextField jTextField_fecha_fundacion;
    private javax.swing.JTextField jTextField_fecha_lanzamiento;
    public javax.swing.JTextField jTextField_genero;
    private javax.swing.JTextField jTextField_interprete_modelo;
    private javax.swing.JTextField jTextField_interprete_voz;
    private javax.swing.JTextField jTextField_motor_videojuego;
    public javax.swing.JTextField jTextField_nombre_empresa;
    private javax.swing.JTextField jTextField_nombre_personaje;
    public javax.swing.JTextField jTextField_nombre_saga;
    private javax.swing.JTextField jTextField_nombre_videojuego;
    public javax.swing.JTextField jTextField_pais_sede;
    private javax.swing.JTextField jTextField_pegi;
    // End of variables declaration//GEN-END:variables
}
